### ISSUE TITLE
PVE equal to 0 for some significant hits (not all) using mlmm while standard error calculation shows NA for all markers

### ISSUE THREAD

**Issue by llama-ops** [jiabowang/GAPIT#110]
Hi, I used the mlmm model option and significant hits were detected; however, the PVE was calculated to be 0 for some of the hits. I assumed that the PVE was being rounded to 0 until I saw in the standard error file that effect sizes were all calculated but all the standard errors were NA for all markers. This was confusing to me because my understanding is that the standard error was required for the PVE calculation. Despite the NAs some of the PVEs were not 0. I also ran the MLM model and everything was calculated normally. Perhaps there is a gap in my understanding?

**Comment by jiabowang** [comment]
Hi, the standard errors are from the estimated model such as MLM, GLM, and so on. However, the multiple loci models such as MLMM, FarmCPU, and BLINK estimated markers' effect by multiple steps. So the standard errors can not be calculated. The PVE values were calculated in a random model. If there is a marker that has a big effect, and shares a strong correlation with another marker. The second marker will show 0 PVE. That means most PVE was taken by the first marker.

**Comment by jiabowang** [comment]
No, the random model is not MLM in the GWAS. That is another model after GWAS, which used all significant markers as random effects to calculate PVE. Based on the calculation speed, we can not get all PVEs for all markers.Please find the PVEs in a file named like GAPIT.Association.PVE.FarmCPU.Sim.csv.

**Comment by llama-ops** [comment]
The PVE calculations I referenced was from looking at the PVE file for the MLMM. Some of the significant hits in the PVE file were calculated to be 0; however, the PVE when running MLM were calculated to be ~5-12% when calculating the PVE for the significant hits identified by MLMM. I am wondering if the MLMM output for PVE is being rounded to 0 or if there might be an error. Thank you for your insights.
