### ISSUE TITLE
[1] "Calling prcomp..."   *** caught segfault *** address 0x7f9c6c292e30, cause 'memory not mapped'

### ISSUE THREAD

**Issue by liuye2024** [jiabowang/GAPIT#121]
Dear sir, I encountered an error while submitting a job on the cluster using the FarmGPU model in GAPIT3 for association analysis. The input includes 370 individuals and 8,031,576 SNPs. The error message suggests a memory issue. Could you please advise me on how to adjust it to ensure smooth analysis? Thank you!
![gapit3error](https://github.com/jiabowang/GAPIT/assets/155537889/6706a0a8-92d5-45af-8d9c-9e7501ce216c)

**Comment by feiyu007** [comment]
hi, liuye, could you tell me, how to solve this problem.

**Comment by liuye2024** [comment]
Please visit this (https://github.com/jiabowang/GAPIT/issues/95) for Dr. Wang's proposed solution to the issue.
“8M markers will make computing problems with PCA in R. Please use other C software to calculate PCA, such as PLINK. Then, put PCs into GAPIT as CV file to perform GWAS.”
Using my genotype data with 8 million SNPs, it has worked a few times after manually adding the PCA file. However, after a month, the same error occurred again, and I am not sure why.
