### ISSUE TITLE
Issues with GBLUP

### ISSUE THREAD

**Issue by statslover123** [jiabowang/GAPIT#58]
I am getting this error when trying gblup in GAPIT

Error in names(x) <- value : 
  'names' attribute [2] must be the same length as the vector [1]
In addition: There were 13 warnings (use warnings() to see them)

This happens after getting VA VE and the kinship file is already calculated.

**Comment by jiabowang** [comment]
Could you show more details about this printed message when the program is done?

**Comment by statslover123** [comment]
I solved by re-downloading GAPIT, I am not sure what the issue was

**Comment by jiabowang** [comment]
Glad to hear you solved the problem.
