### ISSUE TITLE
Error in t(KWO) %*% MASS::ginv(as.matrix(KW)) %*% UW :    requires numeric/complex matrix/vector arguments In addition: There were 50 or more warnings (use warnings() to see the first 50) Error in t(KWO) %*% MASS::ginv(as.matrix(KW)) %*% UW :    requires numeric/complex matrix/vector arguments

### ISSUE THREAD

**Issue by sharifrahmanie** [jiabowang/GAPIT#59]
Hi,
I am getting the above error when including the covariate matrix (myCV).  I also included phenotype, genotype, and kinship files. 
Here are a few lines of myCV file:
Taxa	Q1	Q2	Q3
A3	0.955274	9.7e-05	0.04463
A4	0.999971	1.4e-05	1.5e-05
A7	1.3e-05	1.4e-05	0.999973
A11	0.999971	1.4e-05	1.4e-05

If any other details are required, please let me know. 
Thank you

**Comment by jiabowang** [comment]
The sum total of each row in the  CV file should not be equal to 1. That will make a linear independent problem.

**Comment by k0k0kk0** [comment]
The problem was finally solved

**Comment by k0k0kk0** [comment]
> 

The problem was finally solved!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!I cried to death
