### ISSUE TITLE
Error in FUN(newX[, i], ...) : invalid 'type' (character) of argument

### ISSUE THREAD

**Issue by Vinit2401** [jiabowang/GAPIT#62]
I am trying to use GAPIT function but keep getting this error. I Used basic function : 
myGapit <- GAPIT(Y = myY, GD = myGD, GM = myGM, Model.selection = TRUE, kinship.algorithm="EMMA", model="Blink")

myY, myGD, myGM..all these files are according to gapit input format. I even checked this with demo data and it's the same.
please help...

 myGapit <- GAPIT(Y = myY, GD = myGD, GM = myGM, Model.selection = TRUE, kinship.algorithm="EMMA", model="Blink")
[1] "--------------------- Welcome to GAPIT ----------------------------"
[1] "Blink"
[1] "--------------------Processing traits----------------------------------"
[1] "Phenotype provided!"
[1] "The 1 model in all."
[1] "BLINK"
[1] "GAPIT.DP in process..."
Error in FUN(newX[, i], ...) : invalid 'type' (character) of argument
In addition: Warning messages:
1: 'memory.size()' is no longer supported 
2: 'memory.size()' is no longer supported 
3: 'memory.size()' is no longer supported 
4: In order(as.numeric(as.character(chor_taxa))) :
  NAs introduced by coercion

**Comment by jiabowang** [comment]
Hi,
Could you use traceback() to get information about this error?
