### ISSUE TITLE
'myGM' not found

### ISSUE THREAD

**Issue by jensenjoseph** [jiabowang/GAPIT#67]
Hello,

I am rerunning some data that had previously worked in GAPIT and now it is giving me an error. Currently, I am inputting my HapMap file and phenotyping data in and asking it correct for 3 PCs using FarmCPU. I am getting an error for myGM not being found, but as far as I understand that file only needs to be input for a different genotyping file type. The error code is below.

Error in myGM[, 1] %in% marker.name : object 'myGM' not found

Thank you

**Comment by jiabowang** [comment]
@jensenjoseph ，
Thanks for your report. That is a wrong spelling in Phenotype.afterGWAS function.
Now I have fixed that.

Thank you,
