### ISSUE TITLE
GAPIT  missing data

### ISSUE THREAD

**Issue by isunshine-cc** [jiabowang/GAPIT#70]
When I run the GAPIT  with the numeric genetype file,  the error is  :
GAPIT says: Missing data is not allowed for numerical genotype data
Who can help me to solve this problem?

**Comment by jiabowang** [comment]
If you used GD file, that is numerical genotype data. All genotypes were coded as 0,1,2. In this file, the missing values or other characters are not allowed to calculate.
Please use G file, that is HapMap file, or impute with other software.

**Comment by isunshine-cc** [comment]
Thank you! I will try the happmap file
