### ISSUE TITLE
Discrepancy in Results between FarmCPU and GAPIT's Implementation of FarmCPU

### ISSUE THREAD

**Issue by heitor-mendonca** [jiabowang/GAPIT#77]
Hi, I have encountered an issue with the FarmCPU function in GAPIT and I was hoping you might be able to assist me in resolving it.
When running FarmCPU, following the guidelines in the manual at [FarmCPU Manual](https://zzlab.net/FarmCPU/FarmCPU_help_document.pdf), I obtain a result that is entirely different from the output obtained when using GAPIT's implementation of FarmCPU, as described in the manual at [GAPIT Help Document](https://zzlab.net/GAPIT/gapit_help_document.pdf). The data used in both scenarios are identical, and the code is quite simple:

```
myFarmCPU <- FarmCPU(
  Y=myY,
  GD=myGD,
  GM=myGM,
  CV= myPCA
)

myGAPIT <- GAPIT(
  Y=myY,
  GD=myGD,
  GM=myGM,
  CV= myPCA_GAPIT, 
  model = 'FarmCPU'
)
```

The only difference in the CV is the presence of a column with the taxa, which GAPIT demands, and FarmCPU doesn't.

I'm perplexed by the difference in outcomes, particularly the contrasting p-values and effect sizes in the outputs. Could you shed some light on whether I might be missing a critical step or any particular settings that would reconcile these differences?

Thank you very much for your time and assistance. I look forward to hearing from you soon.

Best regards,
Heitor

**Comment by jiabowang** [comment]
Hi Heitor,
Now, the FarmCPU is different from the original FarmCPU.
The criterion of selected pseudo QTNs into the next model was set as 0.05, rather than 0.01 in the original FarmCPU.
The power testing indicated this strategy is better than the original.

Sincerely,

Jiabo

**Comment by heitor-mendonca** [comment]
Understood, thanks for the help!
