### ISSUE TITLE
GAPIT and TASSEL

### ISSUE THREAD

**Issue by ttian627** [jiabowang/GAPIT#78]
the MLM reulsts were not consistent between GAPIT and TASSEL under the same kinship and covariate files. Is it normal? Looking forward to your reply.

**Comment by jiabowang** [comment]
The results from TASSEL and GAPIT should be the same as each other. I also tested them with demo data. They output the same results.
Could you please introduce your data and code ?

**Comment by ttian627** [comment]
I used the demo data, the input data, code and results are here. Thank you very much!


Yours,


Tian Tian 













At 2023-08-14 16:44:18, "Jiabo Wang" ***@***.***> wrote:

The results from TASSEL and GAPIT should be the same as each other. I also tested them with demo data. They output the same results.
Could you please introduce your data and code ?

**Comment by jiabowang** [comment]
I can not see it. Could you share your code on this communication webpage?

**Comment by ttian627** [comment]
Thre are my code.

1.GAPIT Rscript

library("GAPIT")

#Phenotypic Data

myY <- read.table("mdp_traits.txt", head = TRUE)

#HapMap genotype format

myG <- read.delim("mdp_genotype_test.hmp.txt", head = FALSE)

#Numerical genotype format

#--------------------A pair of Genotypic Data and map files-------------------------------

#myGD <- read.table("mdp_numeric.txt", head = TRUE)

#myGM <- read.table("mdp_SNP_information.txt", head = TRUE)

#Kinship matrix

myKI <- read.table("KSN.txt", head = FALSE)

#covaraite variables (such as population structure represented by Q matrix or PC)

myCV <- read.table("mdp_PC2.txt", head = TRUE)




myGAPIT_MLM <- GAPIT(

  Y=myY[,c(1:2)], #fist column is individual ID, the third columns is days to pollination

  G=myG,  

  KI=myKI,

  CV=myCV,

  model=c("GLM", "MLM"),

  Multiple_analysis=TRUE

  )

2 tassel command

/data/ttian/tools/tassel-5-standalone/run_pipeline.pl -fork1 -h mdp_genotype_test.hmp.txt  -fork2 -r tassel_mdp_traits.txt -fork3 -r tassel_mdp_PC2.txt -fork4 -k tassel_KSN.txt -combine5 -input1 -input2 -input3 -intersect -combine6 -input5 -input4 -mlm -mlmVarCompEst EachMarker -mlmCompressionLevel None -export tassel_mlm_

























At 2023-08-17 11:00:11, "Jiabo Wang" ***@***.***> wrote:

I can not see it. Could you share your code on this communication webpage?

**Comment by jiabowang** [comment]
Hi @ttian627 ,
Thanks for your code.
I noticed that the data format you used is hapmap file. But I used one is a numeric data format.
I think the difference between GAPIT and TASSEL is the imputation.
In the GAPIT, the heterozygous would be imputed as 1, but TASSEL imputed them from an algorithm. That makes different genotypes between GAPIT and TASSEL.
