### ISSUE TITLE
Blink error

### ISSUE THREAD

**Issue by lurens** [jiabowang/GAPIT#98]
I previously (more than one year ago) ran Gapit (version 3.2) on a set of traits using Blink and everything was fine.
Now I re-ran Blink using the last GAPIT version on the same input files to get marker effect, but for some traits I got this error:
"GAPIT.RandomModel beginning..."
logical(0)
Error in if (in_True != 1) { : argument has zero length) "
Have you an idea on what's happening?

Just to check, I ran the old  GAPIT version 3.2 but nothing went right, another error
"Error in if (seqQTN.save != 0 & seqQTN.save != -1 & !is.null(seqQTN)) seqQTN = union(seqQTN,  : 
  condition has length > 1
Many thanks

**Comment by SakaMax** [comment]
Hello GAPIT developer team,

I had the same error as lurens, but I faced the error when I ran GAPIT with GLM, not BLINK. 
My dataset comprises about 1.5 million SNPs in numeric format and phenotype data, and when I ran GAPIT with BLINK using the same dataset, it worked well. 
I attached the output message from GAPIT. I would appreciate any suggestions.
Thanks

[output.txt](https://github.com/jiabowang/GAPIT/files/13722867/output.txt)

**Comment by jiabowang** [comment]
Hey,
Now we added a function to calculate PVE of all significant markers.
If there is no significant markers, this function should be skiped. But from your report, it seems not work.
Please add Random.model=FALSE to skip this function in your case.

**Comment by SakaMax** [comment]
Thank you for your reply! 

Adding the `Random.model=FALSE` parameter to `GAPIT()` overcame the error. 
Then I got the calculation results, Manhattan plots, and so on (yes, there are no significant markers with the GLM, as you guessed.)

Best regards

**Comment by lurens** [comment]
Many thanks
I will try
